export default [
	{
		id: 1,
		startDate: "2021/09",
		endDate: "PRESENT",
		title: "Team Lead - UI",
		company: "Lenskart",
		location: "Hyderabad, India",
		description: [
			"Experienced team lead who managed a 12-person team in revamping Lenskart's front-end architecture, implementing micro-frontend strategies and migrating to Next.js. Improved application performance by optimizing web vitals values, significantly enhancing scalability and overall user experience. Mentored junior developers and established best practices, fostering a culture of continuous improvement within the team.",
		],
		technologies: [
			"JavaScript",
			"TypeScript",
			"React",
			"Next.js",
			"Styled Components",
			"Cypress",
			"Storybook",
			"Verdaccio",
			"Team Management",
		],
		icon: "briefcase" as const,
	},
	{
		id: 2,
		startDate: "2021/02",
		endDate: "2021/08",
		title: "Senior Frontend Developer",
		company: "Lenskart",
		location: "Hyderabad, India",
		description: [
			"Spearheaded the redesign of Lenskart's cart and checkout experience, collaborating with backend developers and product managers to enhance user experience. Integrated multiple payment systems, including Just Pay, resulting in a 21.3% increase in listing-to-checkout conversion rates.",
		],
		technologies: [
			"JavaScript",
			"TypeScript",
			"HTML/CSS",
			"React",
			"Next.js",
			"Styled Components",
			"Cypress",
			"Storybook",
		],
		icon: "briefcase" as const,
	},
	{
		id: 3,
		startDate: "2020/01",
		endDate: "2021/01",
		title: "Senior UI Engineer",
		company: "Darwinbox",
		location: "Hyderabad, India",
		description: [
			"Led a 3-person team in revamping a core business module (20-22% of total revenue) using React with hooks, resulting in a 40% decrease in page load time. Played a pivotal role in redesigning the entire module, collaborating closely with backend developers, UX team, and product managers. This cross-functional effort boosted overall application efficiency by 60% while implementing strategic performance improvement initiatives for sustained growth.",
		],
		technologies: [
			"React",
			"JavaScript",
			"TypeScript",
			"HTML5",
			"CSS3",
			"SCSS",
			"React Testing Library",
			"Redux",
		],
		icon: "briefcase" as const,
	},
	{
		id: 4,
		startDate: "2017/07",
		endDate: "2020/01",
		title: "Software Engineer",
		company: "Zenoti",
		location: "Hyderabad, India",
		description: [
			"Implemented a drag - and - drop Digital Form Builder, increasing form creation efficiency and new product deployment by 80 %.As a core team member, developed Web Store V2, a K2K e - commerce platform using React with Redux.Collaborated with cross - functional teams to deliver the project, contributing to 22.8% business growth.",
		],
		technologies: [
			"React",
			"JavaScript",
			"TypeScript",
			"HTML5",
			"CSS3",
			"SCSS",
			"React Testing Library",
			"Redux",
		],
		icon: "briefcase" as const,
	},
	{
		id: 5,
		startDate: "2015/06",
		endDate: "2017/06",
		title: "Software Engineer",
		company: "Wadi",
		location: "Gurugram, India",
		description: [
			"Redesigned sign-up and promotional coupon generation processes, increasing total users by 25% and reducing coupon misuse. Implemented Google Analytics to gather customer behavior data, which contributed to a 30% increase in overall sales by enabling targeted marketing strategies.",
		],
		technologies: ["HTML5", "CSS3", "JavaScript", "Angular", "Bootstrap", "SCSS"],
		icon: "briefcase" as const,
	},
	{
		id: 6,
		startDate: "2014/05",
		endDate: "2014/08",
		title: "Software Intern",
		company: "Google Summer of Code",
		location: "Remote, India",
		description: [
			"Worked with non-for-profit CiviCRM to migrate their open-source CRM product to mobile friendly new user interface.",
		],
		technologies: ["HTML5", "CSS3", "JavaScript", "jQuery", "PHP", "WordPress"],
		icon: "briefcase" as const,
	},
];
