export default [
	{
		id: 1,
		startDate: "2021/09",
		endDate: "2024/04",
		title: "Team Lead - Full Stack",
		company: "Lenskart",
		location: "Hyderabad, India",
		description: [
			"Leading a 12-person engineering team in building AI-powered features and scalable full-stack architecture serving 10M+ users. Architected and deployed intelligent recommendation systems using ML models, increasing user engagement by 35%. Spearheaded migration to Next.js with server-side rendering, achieving 40% performance improvement in Core Web Vitals.",
			"Integrated AI-driven personalization engines using Python for ML models and chatbot solutions. Built scalable backend services with Node.js/Express handling 100K+ concurrent users, implementing real-time data pipelines and event-driven architectures.",
		],
		technologies: [
			"Node.js/Express",
			"React/Next.js",
			"TypeScript",
			"Python (AI/ML)",
			"Microservices",
			"AWS/GCP",
			"Redis",
			"MongoDB",
			"Team Leadership",
		],
		icon: "briefcase" as const,
	},
	{
		id: 2,
		startDate: "2021/02",
		endDate: "2021/08",
		title: "Senior Full Stack Developer",
		company: "Lenskart",
		location: "Hyderabad, India",
		description: [
			"Architected full-stack checkout system processing $50M+ in transactions, integrating AI-powered fraud detection and recommendation engines. Built real-time inventory management system with predictive analytics for stock optimization.",
			"Developed RESTful APIs and GraphQL services with Node.js handling 10K requests/second. Implemented Python-based ML models for dynamic pricing and personalized product recommendations, increasing conversion rates by 21.3%.",
		],
		technologies: [
			"Node.js/Express",
			"React/Next.js",
			"TypeScript",
			"Python (ML Models)",
			"GraphQL",
			"PostgreSQL",
			"Redis",
			"Docker/Kubernetes",
		],
		icon: "briefcase" as const,
	},
	{
		id: 3,
		startDate: "2020/01",
		endDate: "2021/01",
		title: "Senior Full Stack Engineer",
		company: "Darwinbox",
		location: "Hyderabad, India",
		description: [
			"Built AI-powered HR analytics platform processing data for 500K+ employees, implementing predictive models for employee retention and performance forecasting. Developed full-stack features including real-time dashboards, RESTful APIs, and data visualization tools.",
			"Architected microservices backend with Node.js/Express, implementing event-driven architecture with Kafka. Used Python specifically for ML model deployment and data analysis. Reduced infrastructure costs by 40% through optimization.",
		],
		technologies: [
			"Node.js/Express",
			"React",
			"TypeScript",
			"Python (ML/Analytics)",
			"PostgreSQL",
			"Redis",
			"AWS",
			"Kafka",
		],
		icon: "briefcase" as const,
	},
	{
		id: 4,
		startDate: "2017/07",
		endDate: "2020/01",
		title: "Software Engineer",
		company: "Zenoti",
		location: "Hyderabad, India",
		description: [
			"Developed AI-enhanced Digital Form Builder with intelligent field suggestions and validation, increasing form completion rates by 80%. Built full-stack e-commerce platform with personalized product recommendations using collaborative filtering algorithms.",
			"Implemented real-time analytics pipeline processing 1M+ events daily using Node.js for backend services and Python for data analysis. Created microservices architecture with Docker/Kubernetes, achieving 99.9% uptime.",
		],
		technologies: [
			"Node.js/Express",
			"React/Redux",
			"JavaScript/ES6+",
			"Python (Data Analysis)",
			"MongoDB",
			"Docker",
			"Kubernetes",
			"CI/CD",
		],
		icon: "briefcase" as const,
	},
	{
		id: 5,
		startDate: "2015/06",
		endDate: "2017/06",
		title: "Software Engineer",
		company: "Wadi",
		location: "Gurugram, India",
		description: [
			"Built full-stack authentication system with Node.js backend and Python-based ML algorithms for fraud detection, increasing user acquisition by 25%. Developed data analytics platform processing customer behavior patterns.",
			"Created RESTful APIs and real-time notification services using Node.js/Express and WebSockets. Implemented A/B testing framework and Python-based recommendation engine, contributing to 30% increase in sales.",
		],
		technologies: [
			"Node.js",
			"Angular",
			"Python (ML/Analytics)",
			"MongoDB",
			"WebSockets",
			"A/B Testing",
		],
		icon: "briefcase" as const,
	},
	{
		id: 6,
		startDate: "2014/05",
		endDate: "2014/08",
		title: "Full Stack Development Intern",
		company: "Google Summer of Code",
		location: "Remote, India",
		description: [
			"Developed mobile-first CRM platform with intelligent contact management and automated workflow systems. Built RESTful APIs and integrated third-party services for enhanced functionality.",
		],
		technologies: [
			"Full Stack Development",
			"PHP",
			"JavaScript",
			"MySQL",
			"API Integration",
			"Mobile-First Design",
		],
		icon: "briefcase" as const,
	},
];
